Revert "tk"
pim

deivi@DESKTOP-1SKTSAO MINGW64 ~/curso-pin (main)
$ git revert f90cb7a
error: Your local changes to the following files would be overwritten by merge:
        arquivos/dados.json
        tk.py
Please commit your changes or stash them before you merge.
Aborting
fatal: revert failed

deivi@DESKTOP-1SKTSAO MINGW64 ~/curso-pin (main)
$
This reverts commit f90cb7ac98ca76148326d1553d205f86c787536a.